version: '3.5'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
    env_file:
      - timezone.env

  redis:
    image: redis:rc-alpine
    restart: always
    expose:
      - 6379
    volumes:
      - ./redis/data:/data
    command: redis-server --requirepass '{{REDIS_PASSWORD}}'
    env_file:
      - timezone.env

  nextcloud:
    image: nextcloud:stable
    restart: always
    expose:
      - 80
    volumes:
      - ./data/root:/var/www/html
      - ./data/data:/var/www/html/data
    environment:
      - TRUSTED_PROXIES=caddy
      - NEXTCLOUD_TRUSTED_DOMAINS={{TRUSTED_DOMAINS}}
      - OVERWRITEPROTOCOL=https
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD={{REDIS_PASSWORD}}
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=10240M
    env_file:
      - timezone.env
    depends_on:
      - postgres
      - redis

networks:
  default:
    name: auto-nas
